//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitFlexApparel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        public int Id { get; set; }
        public string Blog_Name { get; set; }
        public Nullable<System.DateTime> Written_On { get; set; }
        public Nullable<System.DateTime> Edited_On { get; set; }
        public Nullable<bool> IsAvailable { get; set; }
        public string Created_By { get; set; }
        public string Blogger_Name { get; set; }
        public string Blog1 { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
