//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitFlexApparel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Custom_Table_2
    {
        public int Id { get; set; }
        public string Column_1 { get; set; }
        public string Column_2 { get; set; }
        public string Column_3 { get; set; }
        public string Column_4 { get; set; }
        public string Column_5 { get; set; }
        public string Column_6 { get; set; }
        public string Column_7 { get; set; }
        public string Column_8 { get; set; }
        public string Column_9 { get; set; }
        public string Column_10 { get; set; }
    }
}
