//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitFlexApparel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inquiry
    {
        public int Id { get; set; }
        public Nullable<int> Product_Id { get; set; }
        public string Product_Name { get; set; }
        public Nullable<int> Number_Of_Samples { get; set; }
        public Nullable<bool> Payment_For_Sample { get; set; }
        public Nullable<bool> Payment_For_Shipment { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Business_Email { get; set; }
        public string Company_Name { get; set; }
        public string Country_Code { get; set; }
        public string Area_Code { get; set; }
        public string Telephone_Number { get; set; }
        public string Ext_Number { get; set; }
        public string Company_Website { get; set; }
        public string Business_Address { get; set; }
        public string City { get; set; }
        public string State_Province { get; set; }
        public string Message { get; set; }
        public string Image_File_1 { get; set; }
        public string Image_File_2 { get; set; }
        public string Image_File_3 { get; set; }
        public string Image_File_4 { get; set; }
        public string Image_File_5 { get; set; }
        public string Custom_Field1 { get; set; }
        public string Custom_Field2 { get; set; }
        public string Custom_Field3 { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
