//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitFlexApparel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int Id { get; set; }
        public Nullable<int> Order_Id { get; set; }
        public Nullable<int> Product_Id { get; set; }
        public string Product_Name { get; set; }
        public string Product_Color { get; set; }
        public string Product_Size { get; set; }
        public string Product_Quantity { get; set; }
        public Nullable<double> Product_Price { get; set; }
        public Nullable<double> Total_Price { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
