//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitFlexApparel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderActionHistories = new HashSet<OrderActionHistory>();
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int Id { get; set; }
        public string Order_No { get; set; }
        public string User_Id { get; set; }
        public Nullable<System.DateTime> Order_Time { get; set; }
        public Nullable<int> Order_Status { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<double> Total_Amount { get; set; }
        public Nullable<int> Total_Products { get; set; }
        public string User_Name { get; set; }
        public string Shipping_Address_Line1 { get; set; }
        public string Shipping_Address_Line2 { get; set; }
        public string Shipping_Address_PostCode { get; set; }
        public string Shipping_Address_City { get; set; }
        public string Shipping_Address_Country { get; set; }
        public string Shipping_Address_PhoneNo { get; set; }
        public string Shipping_Address_Email { get; set; }
        public Nullable<int> Payment_Method { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderActionHistory> OrderActionHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual OrderStatu OrderStatu { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
    }
}
