//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitFlexApparel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderActionHistory
    {
        public int Id { get; set; }
        public Nullable<int> Order_Id { get; set; }
        public Nullable<int> Order_Status { get; set; }
        public Nullable<System.DateTime> Updated_At { get; set; }
        public string Updated_By { get; set; }
        public string Detail { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Order Order { get; set; }
        public virtual OrderStatu OrderStatu { get; set; }
    }
}
