//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitFlexApparel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAddress
    {
        public int Id { get; set; }
        public string User_Id { get; set; }
        public string Address_1 { get; set; }
        public string Address_2 { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string Zip_Code { get; set; }
        public Nullable<bool> IsEnabled { get; set; }
        public Nullable<System.DateTime> Added_On { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
